### PR TITLE
docs: add watch mode

### PR DESCRIPTION
**Pull request by classmatewu**

### CODE REVIEW

**Comment by privatenumber** [comment]
FYI esno is an alias for [tsx](https://github.com/esbuild-kit/tsx), so all documentation from it would apply.

Probably a better idea to make it clearer to read the tsx docs instead.

**Comment by classmatewu** [comment]
I think the relevant documents should be improved to make the existence of esno play a greater value, even a little bit 🤏.

**Comment by classmatewu** [comment]
It's a good thing and I hope tsx and esno get better too⛽️.

**Comment by antfu** [comment]
Thanks. I also lean to have the detailed docs inside tsx to avoid duplication and misalignment

**Pull request closed without merging**
